apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 10s
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      incrementalQuerying: true
    version: 1
    editable: false
