global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets:
          - "rabbitmq:15692"
  - job_name: kafka-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - "kafka-exporter:9308"
  - job_name: kafka-kminion
    metrics_path: /metrics
    static_configs:
      - targets:
          - "kafka-kminion:8802"
